def generate_svg(text, font="Georgia"):

    if not text:
        text = "GlyphForge"

    svg = f"""
    <!-- Generated by GlyphForge -->

    <svg
        width="100%"
        height="220"
        viewBox="0 0 900 220"
        xmlns="http://www.w3.org/2000/svg"
    >

        <defs>

            <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="0%">

                <stop offset="0%" stop-color="#f7d2c4"/>
                <stop offset="100%" stop-color="#ff8e6e"/>

            </linearGradient>

            <filter id="glow">

                <feGaussianBlur stdDeviation="3" result="blur"/>

                <feMerge>

                    <feMergeNode in="blur"/>
                    <feMergeNode in="SourceGraphic"/>

                </feMerge>

            </filter>

        </defs>

        <text
            x="50%"
            y="55%"
            text-anchor="middle"
            font-size="72"
            font-family="{font}"
            fill="url(#grad)"
            letter-spacing="2"
            filter="url(#glow)"
        >
            {text}
        </text>

    </svg>
    """

    return svg